import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [count, setCount] = useState(0);
  const [todoList, setTodoList] = useState(["toto", "titi", "tata"]);
  const [addTodo, setAddTodo] = useState("");
  const [deleteTodo, setDeleteTodo] = useState("");
  const [editTodo, seteditTodo] = useState("");
  const [disabledInput, setDisabledInput] = useState(true);
  const [editableTodo, setEditableTodo] = useState(null);

  const handleChange = (e) => {
    let newTodoList = [...todoList];
    newTodoList[editableTodo] = e.target.value;
    setTodoList(todoList => newTodoList);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello World !</h1>
        <h3>Count : {count}</h3>
        <button onClick={() => setCount(prev => prev+1)}>Click</button>

        <hr className = {styles.hrIndex}></hr>        

        <input onChange={(e) => setAddTodo(addTodo => e.target.value)}/>
        <button onClick={() => setTodoList(todoList => [...todoList, addTodo])}>Add todo</button>

        <hr className = {styles.hrIndex}></hr>

        <input onChange={(e) => setDeleteTodo(deleteTodo => e.target.value)}/>
        <button onClick={() => setTodoList(todoList => todoList.filter(todo => todo !== deleteTodo))}>Delete todo</button>

        <hr className = {styles.hrIndex}></hr>

        {
          todoList.length > 0 && (
            todoList.map((todo, i) => {
              return(
                <div key={i}>
                  <p>{todo}</p>
                    <input value={todo} onChange={handleChange} disabled={editableTodo === i ? false : true}/>
                    <button onClick={(item, index) => setEditableTodo(editableTodo => i)}>Edit</button>
                </div>
              )
            })
          )
        }
      </main>
    </div>
  )
}
