import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [count, setCount] = useState(0);
  const [todoList, setTodoList] = useState(["toto", "titi", "tata"]);
  const [addTodo, setValue] = useState("");
  const [deleteTodo, deleteValue] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello World !</h1>
        <h3>Count : {count}</h3>
        <button onClick={() => setCount(prev => prev+1)}>Click</button>

        <input onChange={(e) => setValue(addTodo => e.target.value)}></input>
        <button onClick={() => setTodoList(todoList => [...todoList, addTodo])}>Add todo</button>

        <hr></hr>

        <input onChange={(e) => deleteValue(deleteTodo => e.target.value)}></input>
        <button onClick={() => setTodoList(todoList => todoList.filter(todo => todo !== deleteTodo))}>Delete todo</button>

        <hr></hr>

        {
          todoList.length > 1 && (
            todoList.map((todo, i) => {
              return(<p key={i}>{todo}</p>)
            })
          )
        }
      </main>
    </div>
  )
}
